#!/usr/bin/env python3
"""Split a change into buckets and write the deterministic half of a change map.

    triage.py --pr 142 --repo nanostack-dev/anchor -o change.json --diff-out review.diff
    triage.py --range main...HEAD -o change.json --diff-out review.diff

change.json gets meta, buckets and tests. review.diff keeps only the files a
human has to read (schema, contract, logic, wiring, docs), so the agent reads
that instead of the whole diff. A summary of where the lines are goes to stderr.
"""

import argparse
import fnmatch
import json
import re
import subprocess
import sys

BUCKETS = [
    ("generated", "Generated", True),
    ("tests", "Tests", True),
    ("schema", "Schema", False),
    ("contract", "Contract", False),
    ("logic", "Logic", False),
    ("wiring", "Wiring & config", False),
    ("docs", "Docs", False),
]

GENERATED = [
    "*.gen.*", "*_gen.go", "*/gen.go", "*/gen/*", "*generated*", "*.pb.go", "*_pb2.py",
    "*/testdata/*", "*__snapshots__*", "*.snap", "*/dist/*",
    "*package-lock.json", "*pnpm-lock.yaml", "*yarn.lock", "*bun.lock*", "*go.sum", "*Cargo.lock",
]
TESTS = ["*_test.go", "*.test.*", "*.spec.*", "*/test/*", "*/tests/*", "*/e2e/*", "*/it/*", "*test_*.py", "*.stories.*"]
SCHEMA = ["*/migrations/*", "*.sql", "*schema.prisma", "*/migrate/*"]
CONTRACT = ["*openapi*.y*ml", "*openapi*.json", "*swagger*", "*.proto", "*.graphql", "*.graphqls", "*.avsc"]
WIRING = [
    "*/module.go", "*/app.go", "*/main.go", "*/fx.go", "*.github/*", "*Dockerfile*", "*docker-compose*",
    "*.tf", "*.tfvars", "*Makefile", "*.toml", "*.ini", "*.env*", "*package.json", "*go.mod",
    "*tsconfig*.json", "*vite.config*", "*.yml", "*.yaml",
]
DOCS = ["*.md", "*.mdx", "*/docs/*", "*.txt", "*.rst"]

GENERATED_MARKER = re.compile(r"(Code generated .* DO NOT EDIT|@generated|auto-generated|autogenerated)", re.I)
TEST_NAME = [
    re.compile(r"^func (Test\w+)\("),
    re.compile(r"^\s*(?:it|test)\(\s*['\"`](.+?)['\"`]"),
    re.compile(r"^\s*def (test_\w+)\("),
]


def run(cmd):
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


def match(path, patterns):
    probe = "/" + path
    return any(fnmatch.fnmatch(probe, p) for p in patterns)


def classify(path, added_head, extra_generated):
    if match(path, GENERATED + extra_generated) or any(GENERATED_MARKER.search(l) for l in added_head):
        return "generated"
    for bucket, patterns in (("tests", TESTS), ("schema", SCHEMA), ("contract", CONTRACT), ("docs", DOCS), ("wiring", WIRING)):
        if match(path, patterns):
            return bucket
    return "logic"


def parse_diff(text):
    files = []
    for chunk in re.split(r"(?=^diff --git )", text, flags=re.M):
        if not chunk.startswith("diff --git "):
            continue
        header = chunk.split("\n", 1)[0]
        path = header.split(" b/", 1)[-1].strip()
        added, removed, head, tests = 0, 0, [], []
        for line in chunk.split("\n"):
            if line.startswith("+++") or line.startswith("---"):
                continue
            if line.startswith("+"):
                added += 1
                if len(head) < 8:
                    head.append(line[1:])
                for rx in TEST_NAME:
                    found = rx.match(line[1:])
                    if found:
                        tests.append(found.group(1))
            elif line.startswith("-"):
                removed += 1
        files.append({"path": path, "add": added, "del": removed, "head": head, "tests": tests, "chunk": chunk})
    return files


def pr_meta(pr, repo):
    fields = "number,title,url,author,baseRefName,headRefName,headRefOid,state,isDraft,additions,deletions,changedFiles,statusCheckRollup,reviewDecision"
    cmd = ["gh", "pr", "view", str(pr), "--json", fields] + (["-R", repo] if repo else [])
    data = json.loads(run(cmd))
    checks = data.get("statusCheckRollup") or []
    conclusions = {(c.get("conclusion") or c.get("status") or "").upper() for c in checks}
    ci = "failing" if conclusions & {"FAILURE", "TIMED_OUT", "CANCELLED", "ERROR"} else (
        "running" if conclusions & {"IN_PROGRESS", "QUEUED", "PENDING"} else ("passing" if checks else "none"))
    owner_repo = repo or re.sub(r"^https://github.com/([^/]+/[^/]+)/pull/.*$", r"\1", data["url"])
    diff = run(["gh", "pr", "diff", str(pr)] + (["-R", repo] if repo else []))
    return {
        "kind": "pr", "repo": owner_repo, "number": data["number"], "title": data["title"], "url": data["url"],
        "author": (data.get("author") or {}).get("login"), "base": data["baseRefName"], "head": data["headRefName"],
        "sha": data["headRefOid"], "state": "draft" if data.get("isDraft") else data["state"].lower(),
        "ci": ci, "review": (data.get("reviewDecision") or "").lower() or None,
    }, diff


def range_meta(rng):
    base, _, head = rng.partition("...")
    head = head or "HEAD"
    diff = run(["git", "diff", rng])
    title = run(["git", "log", "-1", "--format=%s", head]).strip()
    branch = run(["git", "rev-parse", "--abbrev-ref", head]).strip()
    try:
        remote = run(["git", "remote", "get-url", "origin"]).strip()
        repo = re.sub(r"^(?:git@github.com:|https://github.com/)(.+?)(?:\.git)?$", r"\1", remote)
    except subprocess.CalledProcessError:
        repo = None
    return {
        "kind": "wip", "repo": repo, "title": title, "base": base, "head": branch,
        "sha": run(["git", "rev-parse", head]).strip(), "state": "wip", "ci": "none",
    }, diff


def main():
    ap = argparse.ArgumentParser()
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--pr", type=int)
    src.add_argument("--range", help="git range such as main...HEAD, for work with no PR yet")
    ap.add_argument("--repo", help="owner/name when not run inside the repo")
    ap.add_argument("--generated", action="append", default=[], help="extra glob to treat as generated")
    ap.add_argument("-o", "--out", default="change.json")
    ap.add_argument("--diff-out", default="review.diff")
    args = ap.parse_args()

    meta, diff = pr_meta(args.pr, args.repo) if args.pr else range_meta(args.range)
    files = parse_diff(diff)
    for f in files:
        f["bucket"] = classify(f["path"], f["head"], args.generated)

    buckets = []
    for bucket_id, label, skip in BUCKETS:
        members = [f for f in files if f["bucket"] == bucket_id]
        if members:
            buckets.append({
                "id": bucket_id, "label": label, "skip": skip,
                "add": sum(f["add"] for f in members), "del": sum(f["del"] for f in members),
                "files": sorted(([f["path"], f["add"], f["del"]] for f in members), key=lambda r: -(r[1] + r[2])),
            })

    tests = [{"file": f["path"], "names": f["tests"]} for f in files if f["tests"]]
    meta["additions"] = sum(f["add"] for f in files)
    meta["deletions"] = sum(f["del"] for f in files)
    meta["files"] = len(files)

    skeleton = {
        "v": 1, "meta": meta, "summary": "", "verdict": {}, "decisions": [], "schema": None,
        "model": None, "flows": [], "api": [], "rules": [], "watch": [], "buckets": buckets, "tests": tests,
    }
    with open(args.out, "w") as fh:
        json.dump(skeleton, fh, indent=1)

    reviewable = [f for f in files if f["bucket"] not in ("generated", "tests")]
    with open(args.diff_out, "w") as fh:
        fh.write("".join(f["chunk"] for f in reviewable))

    total = meta["additions"] + meta["deletions"] or 1
    print(f"{meta['files']} files, +{meta['additions']} -{meta['deletions']}", file=sys.stderr)
    for b in buckets:
        lines = b["add"] + b["del"]
        mark = "skip" if b["skip"] else "read"
        print(f"  {b['label']:<16} {len(b['files']):>3} files {lines:>7} lines {lines * 100 // total:>3}%  {mark}", file=sys.stderr)
    read = sum(f["add"] + f["del"] for f in reviewable)
    print(f"read {read} lines in {args.diff_out}; {sum(len(t['names']) for t in tests)} test names in {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
